--DELETE FROM dbo.StaffMember;

--go
----insert into staff member table

--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Leena', 'Kristoffersen', '764 Sachtjen Crossing', 'lkristoffersen3@123-reg.co.uk', '10/21/2018', '931245367');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Yetty', 'Littlepage', '97 Ridge Oak Trail', 'ylittlepage2@craigslist.org', '8/15/2014', '931245337');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Darren', 'Mines', '422 Comanche Trail', 'dmines7@creativecommons.org', '10/6/2012', '931242367');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Park', 'Sambells', '827 Dottie Point', 'psambells5@domainmarket.com', '8/22/2011', '931245367');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Killy', 'Jerschke', '77359 Fallview Lane', 'kjerschke8@uiuc.edu', '3/29/2015', '931245307');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Marigold', 'Launder', '606 Harbort Pass', 'mlaunder1@nature.com', '8/1/2012', '931240367');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Marietta', 'Bemand', '6873 Everett Trail', 'mbemand4@flickr.com', '9/1/2013', '931245367');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Chrissy', 'Fouldes', '76 Fulton Alley', 'cfouldes0@forbes.com', '5/21/2012', '931245377');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Tabbie', 'Merrgan', '480 Grasskamp Point', 'tmerrgan9@mapy.cz', '3/17/2013', '931215367');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Robeina', 'Petricas', '3 Huxley Wakle', 'rpetri21@ifeng.com', '6/4/2014', '911245067');
--INSERT INTO dbo.StaffMember (FirstName, LastName, Address, Email, RegisterDate, PhoneNumber)
--        VALUES ('Reina', 'Petri', '3 Huxley Alley', 'rpetri6@ifeng.com', '5/4/2014', '931245067');
