--DELETE FROM dbo.Warehouse;

----insert sample data to Warehouse table

--INSERT INTO dbo.Warehouse (address)
--        VALUES ('35 Farwell Street');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('81648 Sauthoff Drive');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('3 7th Hill');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('3967 Sachs Court');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('1701 Hagan Court');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('1547 Brentwood Road');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('8 Melvin Avenue');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('443 Ohio Plaza');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('63 Beilfuss Park');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('0203 Hansons Way');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('47444 Elgar Pass');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('4 Harper Road');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('11 Northwestern Way');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('32 Ronald Regan Alley');
--INSERT INTO dbo.Warehouse (address)
--        VALUES ('5 Oneill Way');
